name: build-linux-x86_64

on:
  workflow_dispatch:
    inputs:
      xl_converter_ref:
        description: 'XL Converter ref (branch or tag)'
        default: 'unstable'
        required: true
        type: string
      force_clean:
        description: 'Force clean'
        default: false
        type: boolean

permissions:
  actions: write
  contents: read

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6
        with:
          repository: JacobDev1/xl-converter
          ref: ${{ inputs.xl_converter_ref }}
          path: xl-converter

      - name: Purge cache
        if: ${{ inputs.force_clean }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete linux-xl-converter-deps --repo ${{ github.repository }} || true
        
      - name: Restore cached deps
        id: cache-deps
        if: ${{ !inputs.force_clean }}
        uses: actions/cache/restore@v4
        with:
          path: xl-converter/bin
          key: linux-xl-converter-deps

      - name: Build deps
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: cd xl-converter && make deps

      - name: Save deps to cache
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: xl-converter/bin
          key: linux-xl-converter-deps

      - name: Build application
        run: cd xl-converter && make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-builds
          path: xl-converter/dist/

