name: build-macos-universal2

on:
  workflow_dispatch:
    inputs:
      xl_converter_ref:
        description: 'XL Converter ref (branch or tag)'
        default: 'unstable-macos-ci'
        required: true
        type: string
      force_clean:
        description: 'Force clean'
        default: false
        type: boolean

      # Temp inputs for debugging
      install_python:
        description: 'Install Python'
        default: false
        type: boolean
      install_rust:
        description: 'Install Rust'
        default: false
        type: boolean
      build_libjxl:
        description: 'Build libjxl'
        default: false
        type: boolean
      build_libavif:
        description: 'Build libavif'
        default: false
        type: boolean
      build_libjpeg_turbo:
        description: 'Build libjpeg-turbo'
        default: false
        type: boolean
      build_oxipng:
        description: 'Build oxipng'
        default: false
        type: boolean
      build_exiftool:
        description: 'Build exiftool'
        default: false
        type: boolean
      build_imagemagick:
        description: 'Build imagemagick'
        default: false
        type: boolean
      run_tests:
        description: 'Run tests'
        default: false
        type: boolean

permissions:
  actions: write
  contents: read

jobs:
  build-macos-universal2:
    runs-on: macos-15

    steps:
      - name: Purge cache
        if: ${{ inputs.force_clean }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete macports-macos-universal2 || true

      - name: Prepare MacPorts cache dir
        run: |
          sudo mkdir -p /opt/local
          sudo chown -R $USER:admin /opt/local

      - name: Cache MacPorts packages
        id: cache-macports
        if: ${{ !inputs.force_clean }}
        uses: actions/cache/restore@v4
        with:
          path: /opt/local
          key: macports-macos-universal2

      - name: Install MacPorts
        if: ${{ steps.cache-macports.outputs.cache-hit != 'true' }}
        run: |
          set -euox pipefail
          curl -L https://github.com/macports/macports-base/releases/download/v2.11.6/MacPorts-2.11.6-15-Sequoia.pkg -o MacPorts.pkg
          sudo installer -pkg MacPorts.pkg -target /
          echo "/opt/local/bin" >> "$GITHUB_PATH"
          echo "/opt/local/sbin" >> "$GITHUB_PATH"
          sudo /opt/local/bin/port -v selfupdate

      - name: Restore MacPorts
        if: ${{ steps.cache-macports.outputs.cache-hit == 'true' }}
        run: |
          echo "/opt/local/bin" >> "$GITHUB_PATH"
          echo "/opt/local/sbin" >> "$GITHUB_PATH"

      - name: Install build tools
        if: ${{ steps.cache-macports.outputs.cache-hit != 'true' }}
        run: sudo port -N install nasm cmake git wget gtest coreutils ninja gmake gsed llvm-17 clang-17 librsvg yasm

      - name: Install packages from source
        id: install-packages
        if: ${{ steps.cache-macports.outputs.cache-hit != 'true' }}
        env:
          MACOSX_DEPLOYMENT_TARGET: '11.0'
        run: |
          # Setting this will force a recompile which is why I set this after installing heavy packages.
          printf "build_arch    arm64\nmacosx_deployment_target    11.0\n" | sudo tee -a /opt/local/etc/macports/macports.conf > /dev/null
          sudo port -N -s install pkgconfig +universal giflib5 +universal libjpeg-turbo +universal libpng +universal zlib +universal brotli +universal webp +universal libiconv +universal libomp +universal imath +universal glib2 +universal gettext +universal openjpeg +universal lcms2 +universal fontconfig +universal freetype +universal libjxl +universal liblqr +universal tiff +universal libtool +universal

      - name: Save MacPorts cache
        id: cache-macports-save
        uses: actions/cache/save@v4
        if: ${{ always() && steps.cache-macports.outputs.cache-hit != 'true' && steps.install-packages.outcome == 'success' }}
        with:
          path: /opt/local
          key: macports-macos-universal2

      - name: Setup Python
        if: ${{ inputs.install_python }}
        run: |
          set -euox pipefail
          curl -L "https://www.python.org/ftp/python/3.13.10/python-3.13.10-macos11.pkg" -o python.pkg
          sudo installer -pkg python.pkg -target /
          sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.13/bin/python3 /usr/local/bin/python
          sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.13/bin/pip3 /usr/local/bin/pip

      - name: Setup Rust
        if: ${{ inputs.install_rust }}
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          source $HOME/.cargo/env
          rustup target add x86_64-apple-darwin

      - name: Checkout the source code
        uses: actions/checkout@v6
        with:
          repository: JacobDev1/xl-converter
          ref: ${{ inputs.xl_converter_ref }}
          path: xl-converter

      - name: Build libjxl dependency
        if: ${{ inputs.build_libjxl }}
        run: cd xl-converter && make libjxl

      - name: Build libjpeg-turbo dependency
        if: ${{ inputs.build_libjpeg_turbo }}
        run: cd xl-converter && make libjpeg-turbo

      - name: Build Oxipng dependency
        if: ${{ inputs.build_oxipng }}
        run: cd xl-converter && make oxipng

      - name: Build ExifTool dependency
        if: ${{ inputs.build_exiftool }}
        run: cd xl-converter && make exiftool

      - name: Build libavif dependency
        if: ${{ inputs.build_libavif }}
        run: cd xl-converter && make libavif

      - name: Build ImageMagick dependency
        if: ${{ inputs.build_imagemagick }}
        run: cd xl-converter && make imagemagick

      - name: Setup Python environment
        run: |
          cd xl-converter

          # Build
          export MACOSX_DEPLOYMENT_TARGET=11.0
          export ARCHFLAGS="-arch x86_64 -arch arm64"
          export CFLAGS="-arch x86_64 -arch arm64"
          export LDFLAGS="-arch x86_64 -arch arm64"
          export PIP_NO_BINARY=psutil

          python -m venv env_build
          source env_build/bin/activate
          pip install -r requirements.txt --no-binary=:psutil:

          # Compile the bootloader
          export CC="/opt/local/bin/clang-mp-17"
          unset ARCHFLAGS CFLAGS LDFLAGS
          git clone -b v6.11.1 --depth 1 https://github.com/pyinstaller/pyinstaller.git misc/pyinstaller
          cd misc/pyinstaller/bootloader
          python waf all --universal2 --clang
          cd ..
          pip install .
          cd ../..

          # Test
          python -m venv env_dev
          source env_dev/bin/activate
          pip install -r requirements.txt -r requirements_test.txt

      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: |
          cd xl-converter
          source env_dev/bin/activate
          python test.py
          python test_convert.py

      - name: Build
        run: |
          cd xl-converter
          source env_build/bin/activate
          python build.py -b dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal2-build
          path: xl-converter/dist/*.dmg
