name: build-linux-x86_64

on:
  workflow_dispatch:
    inputs:
      xl_converter_ref:
        description: 'XL Converter ref (branch or tag)'
        default: 'unstable'
        required: true
        type: string

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout XL Converter
        uses: actions/checkout@v6
        with:
          repository: JacobDev1/xl-converter
          ref: ${{ inputs.xl_converter_ref }}
          path: xl-converter

      - name: Build
        run: |
          set -euox pipefail
          cd xl-converter
          make build-all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-builds
          path: xl-converter/dist/

