name: build-windows-x86_64

on:
  workflow_dispatch:
    inputs:
      xl_converter_ref:
        description: 'XL Converter ref (branch or tag)'
        default: 'unstable'
        required: true
        type: string
    
jobs:
  build-windows-x86_64:
    runs-on: windows-2022
    
    steps:
      - name: Config git
        run: git config --global core.autocrlf false

      - name: Checkout the source code
        uses: actions/checkout@v6
        with:
          repository: JacobDev1/xl-converter
          ref: ${{ inputs.xl_converter_ref }}
          path: xl-converter

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install bundling tools
        run: choco install innosetup --version 6.2.2 --yes --no-progress --allow-downgrade

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: xl-converter/bin
          key: windows-xl-converter-deps-${{ hashFiles('xl-converter/misc/build_scripts/windows/*.sh') }}

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          cache: false
          install: >-
            git
            cmake
            wget
            make
            base-devel
            autoconf
            automake
            libtool
            nasm
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-gtest
            mingw-w64-x86_64-giflib
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-rust
            mingw-w64-x86_64-7zip
            mingw-w64-x86_64-imagemagick
            mingw-w64-x86_64-libjxl
            mingw-w64-x86_64-aom

      - name: Build deps
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        shell: msys2 {0}
        run: cd xl-converter && make deps

      - name: Build application
        shell: cmd
        run: |
          set MSYSTEM=
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd xl-converter
          python misc/build_scripts/windows/build.py ^
            --python-path "%pythonLocation%\python.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64-builds
          path: xl-converter/dist/
