name: build-windows-x86_64

on:
  workflow_dispatch:
    inputs:
      xl_converter_ref:
        description: 'XL Converter ref (branch or tag)'
        default: 'unstable-win-ci-patches'
        required: true
        type: string
      force_clean:
        description: 'Force clean'
        default: false
        type: boolean
    
permissions:
  actions: write
  contents: read

jobs:
  build-windows-x86_64:
    runs-on: windows-2022
    
    steps:
      - name: Config git
        run: git config --global core.autocrlf false

      - name: Checkout the source code
        uses: actions/checkout@v6
        with:
          repository: JacobDev1/xl-converter
          ref: ${{ inputs.xl_converter_ref }}
          path: xl-converter

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install bundling tools
        run: choco install innosetup --version 6.2.2 --yes --no-progress --allow-downgrade

      - name: Purge cache
        if: ${{ inputs.force_clean }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete windows-xl-converter-deps --repo ${{ github.repository }} || true

      - name: Restore cached deps
        id: cache-deps
        if: ${{ !inputs.force_clean }}
        uses: actions/cache/restore@v4
        with:
          path: xl-converter/bin
          key: windows-xl-converter-deps

      - name: Restore MSYS2 pkg cache
        uses: actions/cache/restore@v4
        with:
          path: C:\msys64\var\cache\pacman\pkg
          key: windows-msys2-pkg-cache

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          cache: false

      # Installing is done in a separate step to prevent msys2 action from cleaning up the pkg cache.
      - name: Install MSYS2 packages
        shell: msys2 {0}
        run: |
          pacman --noconfirm --needed -S \
            git \
            cmake \
            wget \
            make \
            base-devel \
            autoconf \
            automake \
            libtool \
            nasm \
            mingw-w64-x86_64-gcc \
            mingw-w64-x86_64-toolchain \
            mingw-w64-x86_64-cmake \
            mingw-w64-x86_64-ninja \
            mingw-w64-x86_64-gtest \
            mingw-w64-x86_64-giflib \
            mingw-w64-x86_64-libpng \
            mingw-w64-x86_64-libjpeg-turbo \
            mingw-w64-x86_64-rust \
            mingw-w64-x86_64-7zip \
            mingw-w64-x86_64-imagemagick \
            mingw-w64-x86_64-libjxl \
            mingw-w64-x86_64-aom

      - name: Purge MSYS2 pkg cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete windows-msys2-pkg-cache --repo ${{ github.repository }} || true

      - name: Save MSYS2 pkg cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: C:\msys64\var\cache\pacman\pkg
          key: windows-msys2-pkg-cache

      - name: Build deps
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        shell: msys2 {0}
        run: cd xl-converter && make deps

      - name: Save deps to cache
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: xl-converter/bin
          key: windows-xl-converter-deps

      - name: Build application
        shell: cmd
        run: |
          set MSYSTEM=
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd xl-converter
          python misc/build_scripts/windows/build.py ^
            --python-path "%pythonLocation%\python.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64-builds
          path: xl-converter/dist/
